



#Application properties
#server:
#  port: 1043


#AWS properties
cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAW4HO5I55LOJMLJJH
      secretKey: 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

application:
  bucket:
    name: enerdeal

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error



